" Get the defaults that most users want.
unlet! skip_defaults_vim
source $VIMRUNTIME/defaults.vim

" Turn backup off
set nowritebackup
set noswapfile

" Always show the status line
set laststatus=2

" Format the status line
set statusline=\ %f\ %y%(\ [%M%R%H]%)\ \ CWD:\ %{getcwd()}%=%l,%c\ \ %P

" Line numbers
set number

" Tabbing
set expandtab
set softtabstop=4
set shiftwidth=4
set autoindent
set smartindent

" VHDL tabbing
autocmd filetypedetect BufRead,BufNewFile *.vhd set softtabstop=2 | set shiftwidth=2

" Trailing whitespace
highlight TrailWhitespace ctermbg=red guibg=red
autocmd! BufWinEnter * match TrailWhitespace /\s\+$/

" Visualbell only
set belloff=all

" Useful auto-completion
set wildmode=longest,full

" Octave syntax highlighting
autocmd! filetypedetect BufRead,BufNewFile *.m,*.oct,.octaverc set filetype=octave

" Innophase syntax highlighting
autocmd! filetypedetect BufRead,BufNewFile *.reg,*.wfm set filetype=python

" Highlight long lines
set colorcolumn=81
highlight ColorColumn ctermbg=darkgrey guibg=darkgrey

" Folding with <space>
nnoremap <space> za

" C syntax highlighting
unlet c_comment_strings
let c_syntax_for_h = 1
